name: .NET

on:
  push:
    branches: [ feature-TestAutomation ]
  pull_request:
    branches: [ feature-TestAutomation ]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Build and Test
    steps:
    
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
        
    - name: Restore dependencies
      run: dotnet restore ./"Material Obligatorio"/"Obligatorio"/"Ministerio de Turismo"/"Ministerio de Turismo.sln"
    
    - name: Build
      run: dotnet build --configuration Release --no-restore ./"Material Obligatorio"/"Obligatorio"/"Ministerio de Turismo"/"Ministerio de Turismo.sln"


    - name: Upload a Build Artifcat 
      uses: actions/upload-artifact@v2.2.2
      with: 
        name: GitHubActionsDotNetDownloadableArtifact
        path: ./*.*"
        
    
    - name: Test
      run: dotnet test ./"Material Obligatorio/Obligatorio/Ministerio de Turismo/Ministerio de Turismo.sln" -l:trx || true
      shell: bash
    - if: always()
      name: Report
      uses: dorny/test-reporter@v1
      with:
        name: DotNET Tests Results
        path: '**/*.trx'
        reporter: dotnet-trx
        fail-on-error: 'false'

    - name: Upload test results
      uses: actions/upload-artifact@v2.2.2
      with:
        name: GitHubActionsTestsResults
        path: '**/*.trx'
