name: build-test-dotnet

on:
  push:
    branches: [ main, feature-CodeCoverageAction ]
  pull_request:
    branches: [ main  ]

jobs:
  build:

    runs-on: windows-latest
    name: Build and Test
    steps:

    - name: Checkout 
      uses: actions/checkout@v3
   
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
  
    - name: Restore dependencies
      run: dotnet restore ./"Material Obligatorio"/"Obligatorio"/"Ministerio de Turismo"
      
    - name: Build
      run: dotnet build --configuration Release --no-restore ./"Material Obligatorio"/"Obligatorio"/"Ministerio de Turismo" 


    - name: Upload a Build Artifcat 
      uses: actions/upload-artifact@v2.2.2
      with: 
        name: BuildRelease
        path: './Material Obligatorio/Obligatorio/Ministerio de Turismo/MinTur.WebApi/bin/Release/netcoreapp3.1/*'
        
    
    - name: Test
      run: dotnet test ./"Material Obligatorio/Obligatorio/Ministerio de Turismo/Ministerio de Turismo.sln"  --collect:"Code Coverage" --results-directory "TestCoverageResults" --filter FullyQualifiedName!~SpecFlow -l:trx || true
      shell: bash
    - if: always()
      name: Report
      uses: dorny/test-reporter@v1
      with:
        name: DotNET Tests Results 
        path: '**/*.trx'
        reporter: dotnet-trx
        fail-on-error: 'false'

    - name: Upload test results
      uses: actions/upload-artifact@v2.2.2
      with:
        name: GitHubActionsTestsResults
        path: '**/*.trx'
        
    # Code coverage
    
    - name: Install dotenet-coverage
      run: dotnet tool install --global dotnet-coverage
    
    - name: Merge Projects Tests
      run: cd  ./"Material Obligatorio/Obligatorio/Ministerio de Turismo/TestCoverageResults" |
          dotnet-coverage merge  -r . -f xml
    
    - name: Install reportgenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.1.9
      
    - name: Generate report
      run: cd ./"Material Obligatorio/Obligatorio/Ministerio de Turismo/TestCoverageResults" | 
          reportgenerator "-reports:output.coverage.xml" "-targetdir:out"
    
