name: Build Angular

on:
  push:
    branches: [ feature-CloudDeploy ]
  pull_request:
    branches: [ temp ]

env:
  GITHUB_SHA: ${{ github.sha }}
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  IBM_CLOUD_REGION: ${{ secrets.IBM_CLOUD_REGION }}
  ICR_NAMESPACE: ${{ secrets.ICR_NAMESPACE }}
  IKS_CLUSTER: ${{ secrets.IKS_CLUSTER }} # name or id of cluster
  BACKEND_ENDPOINT: ${{ secrets.BACKEND_ENDPOINT}}


jobs:
  build-angular:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      
      - name: Setup Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Build
        run: |
          npm install
          npm run build
        working-directory: './Material Obligatorio/Obligatorio/MinTurFrontend'
        
      - name: Upload build results
        uses: actions/upload-artifact@v2.2.2
        with:
          name: FrontDist
          path: './Material Obligatorio/Obligatorio/MinTurFrontend/dist/MinTurFrontend'
          
      # DEPLOY TO STAGING
      
      # Download and Install IBM Cloud CLI
      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version
          ibmcloud config --check-version=false
          ibmcloud plugin install -f kubernetes-service
          ibmcloud plugin install -f container-registry
         
      # Authenticate with IBM Cloud CLI 
      - name: Authenticate with IBM Cloud CLI
        run: |
          ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r "${IBM_CLOUD_REGION}" -g Default
          
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}
      
      # Changes endpoint of backend
      - uses: actions/checkout@v2
      - name: Find and Replace endpoint
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: 'http://localhost:5000/api'
          replace: '${BACKEND_ENDPOINT}'
          include: "./Material Obligatorio/Obligatorio/MinTurFrontend/dist/MinTurFrontend/**"
      
      # Build the Docker image
      - name: Copy file for docker
        run: cd  './Material Obligatorio/Obligatorio/MinTurFrontend/
          
      - name: Docker build    
        run:  docker build -t "ivanmonjardin/agil-front":"$GITHUB_SHA" \
              --build-arg GITHUB_SHA="${GITHUB_SHA}" \
              --build-arg GITHUB_REF="${GITHUB_REF}" .
      
      # Push the image to DockerHub
      - name: Push the image to DockerHub
        run: |
          docker push "ivanmonjardin/agil-front":"${GITHUB_SHA}"
          docker tag "ivanmonjardin/agil-front":"${GITHUB_SHA}" "ivanmonjardin/agil-front" 
          docker push "ivanmonjardin/agil-front"
          
      # Deploy the Docker image to the IBM Cloud Kubernetes cluster
      - name: Deploy to IKS
        run: |
          ibmcloud ks cluster config --cluster ${IKS_CLUSTER}
          kubectl config current-context
          kubectl rollout restart deployment/front
