name: .NET

on:
  push:
    branches: [ feature-TestAutomation ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Test
      run: dotnet test ./"Material Obligatorio"/"Obligatorio"/"Ministerio de Turismo"/"Ministerio de Turismo.sln" -l:trx || true
      shell: bash
    - if: always()
      name: Report
      uses: dorny/test-reporter@v1
      with:
        name: DotNET Tests Results
        path: '**/*.trx'
        reporter: dotnet-trx
        fail-on-error: 'false'

    - name: Upload a Build Artificat 
      uses: actions/upload-artifact@v2.2.2
      with: 
        name: GitHubActionsDotNetDownloadableArtifact
        path: ./"Material Obligatorio/Obligatorio/Ministerio de Turismo/MinTur.WebApi/bin/release/netcoreapp3.1/*.*"

    - name: Upload test results
      uses: actions/upload-artifact@v2.2.2
      with:
        name: GitHubActionsTestsResults
        path: '**/*.trx'
